const START_IMAGE_CAPTURING = "START_IMAGE_CAPTURING";
const STOP_IMAGE_CAPTURING = "STOP_IMAGE_CAPTURING";
const SHOW_IMAGE_ARRAY = "SHOW_IMAGE_ARRAY";
const SAVE_IMAGE_ARRAY = "SAVE_IMAGE_ARRAY";

module.exports = {
  START_IMAGE_CAPTURING,
  STOP_IMAGE_CAPTURING,
  SHOW_IMAGE_ARRAY,
  SAVE_IMAGE_ARRAY,
};
